apiVersion: apps/v1
kind: Deployment
metadata:
  name: Alexion
  labels:
    app: Alexion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Alexion
  template:
    metadata:
      labels:
        app: Alexion
    spec:
      containers:
        - name: Alexion
          image: 274127640471.dkr.ecr.us-east-2.amazonaws.com/primuslearning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
